INSERT INTO fhirfox.generator_rule (
    ig_name, ig_version, resource_type, source_table, source_column,
    fhir_path, data_type, is_required, transform_kind, mapping_key, reference_target, sort_order
) VALUES
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient_identifier', 'id_type', 'Patient.identifier[].type.coding[0].code', 'string', TRUE, 'code_map', 'Patient.identifier.type', NULL, 1),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient_identifier', 'id_number', 'Patient.identifier[].value', 'string', TRUE, 'copy', NULL, NULL, 2),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient', 'name', 'Patient.name[0]:usual.text', 'string', TRUE, 'copy', NULL, NULL, 3),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient', 'gender', 'Patient.gender', 'string', TRUE, 'code_map', 'Patient.gender', NULL, 4),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient', 'birthday', 'Patient.birthDate', 'date', TRUE, 'copy', NULL, NULL, 5),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient_telecom', 'telecom_system', 'Patient.telecom[].system', 'string', FALSE, 'copy', NULL, NULL, 6),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient_telecom', 'telecom_use', 'Patient.telecom[].use', 'string', FALSE, 'copy', NULL, NULL, 7),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient_telecom', 'telecom_value', 'Patient.telecom[].value', 'string', FALSE, 'copy', NULL, NULL, 8),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient_address', 'address_text', 'Patient.address[].text', 'string', FALSE, 'copy', NULL, NULL, 9),
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'twcore.patient', 'organization_id', 'Patient.managingOrganization.reference', 'string', FALSE, 'build_reference', NULL, 'Organization', 10),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'allergy_id', 'AllergyIntolerance.id', 'string', FALSE, 'copy', NULL, NULL, 1),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'clinical_status', 'AllergyIntolerance.clinicalStatus.coding[0].code', 'string', TRUE, 'code_map', 'AllergyIntolerance.clinicalStatus', NULL, 2),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'verification_status', 'AllergyIntolerance.verificationStatus.coding[0].code', 'string', FALSE, 'code_map', 'AllergyIntolerance.verificationStatus', NULL, 3),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'type', 'AllergyIntolerance.type', 'string', FALSE, 'code_map', 'AllergyIntolerance.type', NULL, 4),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'category', 'AllergyIntolerance.category[0]', 'string', FALSE, 'code_map', 'AllergyIntolerance.category', NULL, 5),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'criticality', 'AllergyIntolerance.criticality', 'string', FALSE, 'code_map', 'AllergyIntolerance.criticality', NULL, 6),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'allergy_code', 'AllergyIntolerance.code.coding[0].code', 'string', TRUE, 'code_map', 'AllergyIntolerance.allergyCode', NULL, 7),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'patient_id', 'AllergyIntolerance.patient.reference', 'string', TRUE, 'build_reference', NULL, 'Patient', 8),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'encounter_id', 'AllergyIntolerance.encounter.reference', 'string', FALSE, 'build_reference', NULL, 'Encounter', 9),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'onset_date', 'AllergyIntolerance.onsetDateTime', 'dateTime', FALSE, 'copy', NULL, NULL, 10),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'recorded_date', 'AllergyIntolerance.recordedDate', 'dateTime', TRUE, 'copy', NULL, NULL, 11),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'recorder_id', 'AllergyIntolerance.recorder.reference', 'string', TRUE, 'build_reference', NULL, 'Practitioner', 12),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'note', 'AllergyIntolerance.note[0].text', 'string', FALSE, 'copy', NULL, NULL, 13),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'reaction_substance', 'AllergyIntolerance.reaction[0].substance.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 14),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'manifestation', 'AllergyIntolerance.reaction[0].manifestation[0].coding[0].code', 'string', TRUE, 'copy', NULL, NULL, 15),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'severity', 'AllergyIntolerance.reaction[0].severity', 'string', TRUE, 'code_map', 'AllergyIntolerance.severity', NULL, 16),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'twcore.allergy_intolerance', 'exposure_route', 'AllergyIntolerance.reaction[0].exposureRoute.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 17),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner', 'practitioner_id', 'Practitioner.id', 'string', FALSE, 'copy', NULL, NULL, 1),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner', 'active', 'Practitioner.active', 'boolean', FALSE, 'copy', NULL, NULL, 2),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_identifier', 'id_type', 'Practitioner.identifier[].type.coding[0].code', 'string', TRUE, 'copy', NULL, NULL, 3),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_identifier', 'id_number', 'Practitioner.identifier[].value', 'string', TRUE, 'copy', NULL, NULL, 4),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner', 'name', 'Practitioner.name[0].text', 'string', TRUE, 'copy', NULL, NULL, 5),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner', 'gender', 'Practitioner.gender', 'string', FALSE, 'code_map', 'Practitioner.gender', NULL, 6),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner', 'birthday', 'Practitioner.birthDate', 'date', FALSE, 'copy', NULL, NULL, 7),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_telecom', 'telecom_system', 'Practitioner.telecom[].system', 'string', FALSE, 'copy', NULL, NULL, 8),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_telecom', 'telecom_use', 'Practitioner.telecom[].use', 'string', FALSE, 'copy', NULL, NULL, 9),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_telecom', 'telecom_value', 'Practitioner.telecom[].value', 'string', FALSE, 'copy', NULL, NULL, 10),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_address', 'address_text', 'Practitioner.address[].text', 'string', FALSE, 'copy', NULL, NULL, 11),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_qualification', 'qualification_code', 'Practitioner.qualification[].code.coding[0].code', 'string', FALSE, 'code_map', 'Practitioner.qualification.code', NULL, 12),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'twcore.practitioner_qualification', 'qualification_issuer_id', 'Practitioner.qualification[].issuer.reference', 'string', FALSE, 'build_reference', NULL, 'Organization', 13),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization', 'organization_id', 'Organization.id', 'string', FALSE, 'copy', NULL, NULL, 1),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization', 'active', 'Organization.active', 'boolean', FALSE, 'copy', NULL, NULL, 2),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_identifier', 'id_type', 'Organization.identifier[].type.coding[0].code', 'string', TRUE, 'copy', NULL, NULL, 3),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_identifier', 'id_number', 'Organization.identifier[].value', 'string', TRUE, 'copy', NULL, NULL, 4),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization', 'type', 'Organization.type[0].coding[0].code', 'string', FALSE, 'code_map', 'Organization.type', NULL, 5),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization', 'name', 'Organization.name', 'string', TRUE, 'copy', NULL, NULL, 6),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization', 'alias', 'Organization.alias[0]', 'string', FALSE, 'copy', NULL, NULL, 7),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_telecom', 'telecom_system', 'Organization.telecom[].system', 'string', FALSE, 'copy', NULL, NULL, 8),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_telecom', 'telecom_use', 'Organization.telecom[].use', 'string', FALSE, 'copy', NULL, NULL, 9),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_telecom', 'telecom_value', 'Organization.telecom[].value', 'string', FALSE, 'copy', NULL, NULL, 10),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_address', 'address_text', 'Organization.address[].text', 'string', FALSE, 'copy', NULL, NULL, 11),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization', 'part_of_id', 'Organization.partOf.reference', 'string', FALSE, 'build_reference', NULL, 'Organization', 12),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_contact', 'contact_purpose', 'Organization.contact[].purpose.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 13),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_contact', 'contact_name', 'Organization.contact[].name.text', 'string', FALSE, 'copy', NULL, NULL, 14),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'twcore.organization_contact', 'contact_telecom', 'Organization.contact[].telecom[0].value', 'string', FALSE, 'copy', NULL, NULL, 15),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'role_id', 'PractitionerRole.id', 'string', FALSE, 'copy', NULL, NULL, 1),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'active', 'PractitionerRole.active', 'boolean', FALSE, 'copy', NULL, NULL, 2),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'practitioner_id', 'PractitionerRole.practitioner.reference', 'string', FALSE, 'build_reference', NULL, 'Practitioner', 3),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'organization_id', 'PractitionerRole.organization.reference', 'string', FALSE, 'build_reference', NULL, 'Organization', 4),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'location_id', 'PractitionerRole.location[0].reference', 'string', FALSE, 'build_reference', NULL, 'Location', 5),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'role_code', 'PractitionerRole.code[0].coding[0].code', 'string', FALSE, 'code_map', 'PractitionerRole.code', NULL, 6),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'specialty_code', 'PractitionerRole.specialty[0].coding[0].code', 'string', FALSE, 'code_map', 'PractitionerRole.specialty', NULL, 7),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'period_start', 'PractitionerRole.period.start', 'dateTime', FALSE, 'copy', NULL, NULL, 8),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role', 'period_end', 'PractitionerRole.period.end', 'dateTime', FALSE, 'copy', NULL, NULL, 9),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role_telecom', 'telecom_system', 'PractitionerRole.telecom[].system', 'string', FALSE, 'copy', NULL, NULL, 10),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role_telecom', 'telecom_use', 'PractitionerRole.telecom[].use', 'string', FALSE, 'copy', NULL, NULL, 11),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'twcore.practitioner_role_telecom', 'telecom_value', 'PractitionerRole.telecom[].value', 'string', FALSE, 'copy', NULL, NULL, 12),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'encounter_id', 'Encounter.id', 'string', FALSE, 'copy', NULL, NULL, 1),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'identifier', 'Encounter.identifier[0].value', 'string', FALSE, 'copy', NULL, NULL, 2),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'status', 'Encounter.status', 'string', TRUE, 'code_map', 'Encounter.status', NULL, 3),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'class', 'Encounter.class.code', 'string', TRUE, 'code_map', 'Encounter.class', NULL, 4),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'service_type', 'Encounter.serviceType.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 5),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'patient_id', 'Encounter.subject.reference', 'string', TRUE, 'build_reference', NULL, 'Patient', 6),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'period_start', 'Encounter.period.start', 'dateTime', FALSE, 'copy', NULL, NULL, 7),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'period_end', 'Encounter.period.end', 'dateTime', FALSE, 'copy', NULL, NULL, 8),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'service_provider_id', 'Encounter.serviceProvider.reference', 'string', FALSE, 'build_reference', NULL, 'Organization', 9),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'part_of_id', 'Encounter.partOf.reference', 'string', FALSE, 'build_reference', NULL, 'Encounter', 10),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'participant_type', 'Encounter.participant[0].type[0].coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 11),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'practitioner_id', 'Encounter.participant[0].individual.reference', 'string', TRUE, 'build_reference', NULL, 'Practitioner', 12),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'location_id', 'Encounter.location[0].location.reference', 'string', TRUE, 'build_reference', NULL, 'Location', 13),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'location_status', 'Encounter.location[0].status', 'string', FALSE, 'copy', NULL, NULL, 14),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'condition_id', 'Encounter.diagnosis[0].condition.reference', 'string', TRUE, 'build_reference', NULL, 'Condition', 15),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'diagnosis_use', 'Encounter.diagnosis[0].use.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 16),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'admit_source', 'Encounter.hospitalization.admitSource.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 17),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'twcore.encounter', 'discharge_disposition', 'Encounter.hospitalization.dischargeDisposition.coding[0].code', 'string', FALSE, 'copy', NULL, NULL, 18)
ON CONFLICT (ig_name, ig_version, resource_type, source_table, source_column, fhir_path) DO UPDATE SET
    data_type = EXCLUDED.data_type,
    is_required = EXCLUDED.is_required,
    transform_kind = EXCLUDED.transform_kind,
    mapping_key = EXCLUDED.mapping_key,
    reference_target = EXCLUDED.reference_target,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE;

INSERT INTO fhirfox.resource_profile (
    ig_name, ig_version, resource_type, profile_url
) VALUES
    ('tw.gov.mohw.twcore', '1.0.0', 'Patient', 'https://twcore.mohw.gov.tw/ig/twcore/StructureDefinition/Patient-twcore'),
    ('tw.gov.mohw.twcore', '1.0.0', 'AllergyIntolerance', 'https://twcore.mohw.gov.tw/ig/twcore/StructureDefinition/AllergyIntolerance-twcore'),
    ('tw.gov.mohw.twcore', '1.0.0', 'Practitioner', 'https://twcore.mohw.gov.tw/ig/twcore/StructureDefinition/Practitioner-twcore'),
    ('tw.gov.mohw.twcore', '1.0.0', 'Organization', 'https://twcore.mohw.gov.tw/ig/twcore/StructureDefinition/Organization-twcore'),
    ('tw.gov.mohw.twcore', '1.0.0', 'PractitionerRole', 'https://twcore.mohw.gov.tw/ig/twcore/StructureDefinition/PractitionerRole-twcore'),
    ('tw.gov.mohw.twcore', '1.0.0', 'Encounter', 'https://twcore.mohw.gov.tw/ig/twcore/StructureDefinition/Encounter-twcore')
ON CONFLICT (ig_name, ig_version, resource_type) DO UPDATE SET
    profile_url = EXCLUDED.profile_url,
    is_active = TRUE;
