INSERT INTO fhirfox.code_mapping (
    mapping_key, source_code, target_code, target_display,
    target_system, display_zh_tw, group_name
) VALUES
    ('Patient.gender', 'male', 'male', 'Male', 'http://hl7.org/fhir/administrative-gender', '男性', NULL),
    ('Patient.gender', 'female', 'female', 'Female', 'http://hl7.org/fhir/administrative-gender', '女性', NULL),
    ('Patient.gender', 'other', 'other', 'Other', 'http://hl7.org/fhir/administrative-gender', '其他', NULL),
    ('Patient.gender', 'unknown', 'unknown', 'Unknown', 'http://hl7.org/fhir/administrative-gender', '未知', NULL),
    ('Patient.identifier.type', 'NNxxx', 'NNxxx', 'National Person Identifier where the xxx is the ISO table 3166 3-character (alphabetic) country code', 'http://terminology.hl7.org/CodeSystem/v2-0203', '身分證字號', NULL),
    ('Patient.identifier.type', 'PRC', 'PRC', 'Permanent Resident Card Number', 'http://terminology.hl7.org/CodeSystem/v2-0203', '居留證號', NULL),
    ('Patient.identifier.type', 'PPN', 'PPN', 'Passport number', 'http://terminology.hl7.org/CodeSystem/v2-0203', '護照號碼', NULL),
    ('Patient.identifier.type', 'MR', 'MR', 'Medical record number', 'http://terminology.hl7.org/CodeSystem/v2-0203', '病歷號', NULL),
    ('AllergyIntolerance.clinicalStatus', 'active', 'active', 'Active', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', '活躍', NULL),
    ('AllergyIntolerance.clinicalStatus', 'inactive', 'inactive', 'Inactive', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', '不活躍', NULL),
    ('AllergyIntolerance.clinicalStatus', 'resolved', 'resolved', 'Resolved', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', '已緩解', NULL),
    ('AllergyIntolerance.verificationStatus', 'unconfirmed', 'unconfirmed', 'Unconfirmed', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', '未確認', NULL),
    ('AllergyIntolerance.verificationStatus', 'confirmed', 'confirmed', 'Confirmed', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', '已確認', NULL),
    ('AllergyIntolerance.verificationStatus', 'refuted', 'refuted', 'Refuted', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', '已排除', NULL),
    ('AllergyIntolerance.verificationStatus', 'entered-in-error', 'entered-in-error', 'Entered in Error', 'http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', '輸入錯誤', NULL),
    ('AllergyIntolerance.type', 'allergy', 'allergy', 'Allergy', 'http://hl7.org/fhir/allergy-intolerance-type', '過敏', NULL),
    ('AllergyIntolerance.type', 'intolerance', 'intolerance', 'Intolerance', 'http://hl7.org/fhir/allergy-intolerance-type', '不耐症', NULL),
    ('AllergyIntolerance.category', 'food', 'food', 'Food', 'http://hl7.org/fhir/allergy-intolerance-category', '食物', NULL),
    ('AllergyIntolerance.category', 'medication', 'medication', 'Medication', 'http://hl7.org/fhir/allergy-intolerance-category', '藥物', NULL),
    ('AllergyIntolerance.category', 'environment', 'environment', 'Environment', 'http://hl7.org/fhir/allergy-intolerance-category', '環境', NULL),
    ('AllergyIntolerance.category', 'biologic', 'biologic', 'Biologic', 'http://hl7.org/fhir/allergy-intolerance-category', '生物製劑', NULL),
    ('AllergyIntolerance.criticality', 'low', 'low', 'Low Risk', 'http://hl7.org/fhir/allergy-intolerance-criticality', '低風險', NULL),
    ('AllergyIntolerance.criticality', 'high', 'high', 'High Risk', 'http://hl7.org/fhir/allergy-intolerance-criticality', '高風險', NULL),
    ('AllergyIntolerance.criticality', 'unable-to-assess', 'unable-to-assess', 'Unable to Assess Risk', 'http://hl7.org/fhir/allergy-intolerance-criticality', '無法評估', NULL),
    ('AllergyIntolerance.severity', 'mild', 'mild', 'Mild', 'http://hl7.org/fhir/reaction-event-severity', '輕度', NULL),
    ('AllergyIntolerance.severity', 'moderate', 'moderate', 'Moderate', 'http://hl7.org/fhir/reaction-event-severity', '中度', NULL),
    ('AllergyIntolerance.severity', 'severe', 'severe', 'Severe', 'http://hl7.org/fhir/reaction-event-severity', '重度', NULL),
    ('Practitioner.gender', 'male', 'male', 'Male', 'http://hl7.org/fhir/administrative-gender', '男性', NULL),
    ('Practitioner.gender', 'female', 'female', 'Female', 'http://hl7.org/fhir/administrative-gender', '女性', NULL),
    ('Practitioner.gender', 'other', 'other', 'Other', 'http://hl7.org/fhir/administrative-gender', '其他', NULL),
    ('Practitioner.gender', 'unknown', 'unknown', 'Unknown', 'http://hl7.org/fhir/administrative-gender', '未知', NULL),
    ('Organization.type', 'prov', 'prov', 'Healthcare Provider', 'http://terminology.hl7.org/CodeSystem/organization-type', '醫療服務提供者/醫療機構', NULL),
    ('Organization.type', 'dept', 'dept', 'Hospital Department', 'http://terminology.hl7.org/CodeSystem/organization-type', '醫院科部', NULL),
    ('Organization.type', 'team', 'team', 'Organizational team', 'http://terminology.hl7.org/CodeSystem/organization-type', '組織團隊', NULL),
    ('Organization.type', 'govt', 'govt', 'Government', 'http://terminology.hl7.org/CodeSystem/organization-type', '政府機構', NULL),
    ('Organization.type', 'ins', 'ins', 'Insurance Company', 'http://terminology.hl7.org/CodeSystem/organization-type', '保險機構', NULL),
    ('Organization.type', 'pay', 'pay', 'Payer', 'http://terminology.hl7.org/CodeSystem/organization-type', '付款方 (例如健保署)', NULL),
    ('Organization.type', 'edu', 'edu', 'Educational Institute', 'http://terminology.hl7.org/CodeSystem/organization-type', '教育機構', NULL),
    ('Organization.type', 'reli', 'reli', 'Religious Institution', 'http://terminology.hl7.org/CodeSystem/organization-type', '宗教機構', NULL),
    ('Organization.type', 'crs', 'crs', 'Clinical Research Sponsor', 'http://terminology.hl7.org/CodeSystem/organization-type', '臨床研究贊助者', NULL),
    ('Organization.type', 'cg', 'cg', 'Community Group', 'http://terminology.hl7.org/CodeSystem/organization-type', '社區團體', NULL),
    ('Organization.type', 'bus', 'bus', 'Non-Healthcare Business or Corporation', 'http://terminology.hl7.org/CodeSystem/organization-type', '非醫療企業或公司', NULL),
    ('Organization.type', 'ntwk', 'ntwk', 'Network', 'http://terminology.hl7.org/CodeSystem/organization-type', '醫療網絡', NULL),
    ('Encounter.class', 'AMB', 'AMB', 'ambulatory', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '門診', NULL),
    ('Encounter.class', 'EMER', 'EMER', 'emergency', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '急診', NULL),
    ('Encounter.class', 'FLD', 'FLD', 'field', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '現場', NULL),
    ('Encounter.class', 'HH', 'HH', 'home health', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '居家照護', NULL),
    ('Encounter.class', 'IMP', 'IMP', 'inpatient encounter', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '住院', NULL),
    ('Encounter.class', 'ACUTE', 'ACUTE', 'inpatient acute', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '急性住院', NULL),
    ('Encounter.class', 'NONAC', 'NONAC', 'inpatient non-acute', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '非急性住院', NULL),
    ('Encounter.class', 'OBSENC', 'OBSENC', 'observation encounter', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '留院觀察', NULL),
    ('Encounter.class', 'PRENC', 'PRENC', 'pre-admission', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '入院前', NULL),
    ('Encounter.class', 'SS', 'SS', 'short stay', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '短期停留', NULL),
    ('Encounter.class', 'VR', 'VR', 'virtual', 'http://terminology.hl7.org/CodeSystem/v3-ActCode', '遠距看診', NULL),
    ('Encounter.status', 'planned', 'planned', 'Planned', 'http://hl7.org/fhir/encounter-status', '計畫中/預約', NULL),
    ('Encounter.status', 'arrived', 'arrived', 'Arrived', 'http://hl7.org/fhir/encounter-status', '已報到', NULL),
    ('Encounter.status', 'triaged', 'triaged', 'Triaged', 'http://hl7.org/fhir/encounter-status', '已檢傷分類', NULL),
    ('Encounter.status', 'in-progress', 'in-progress', 'In Progress', 'http://hl7.org/fhir/encounter-status', '看診中', NULL),
    ('Encounter.status', 'onleave', 'onleave', 'On Leave', 'http://hl7.org/fhir/encounter-status', '請假外出', NULL),
    ('Encounter.status', 'finished', 'finished', 'Finished', 'http://hl7.org/fhir/encounter-status', '已完診', NULL),
    ('Encounter.status', 'cancelled', 'cancelled', 'Cancelled', 'http://hl7.org/fhir/encounter-status', '取消就醫', NULL),
    ('Encounter.status', 'entered-in-error', 'entered-in-error', 'Entered in Error', 'http://hl7.org/fhir/encounter-status', '輸入錯誤', NULL),
    ('Encounter.status', 'unknown', 'unknown', 'Unknown', 'http://hl7.org/fhir/encounter-status', '未知', NULL),
    ('AllergyIntolerance.allergyCode', 'Al-N0001', '716186003', 'No known allergy', 'http://snomed.info/sct', '無已知過敏', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-N0002', '409137002', 'No known history of drug allergy', 'http://snomed.info/sct', '無已知藥物過敏史', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-N0003', '428197003', 'No known insect allergy', 'http://snomed.info/sct', '無已知昆蟲過敏', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-N0004', '428607008', 'No known environmental allergy', 'http://snomed.info/sct', '無已知環境過敏', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-N0005', '429625007', 'No known food allergy', 'http://snomed.info/sct', '無已知食物過敏', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-N0006', '716184000', 'No known latex allergy', 'http://snomed.info/sct', '無已知乳膠過敏', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-N0007', '716220001', 'No known animal allergy', 'http://snomed.info/sct', '無已知動物過敏', '無已知過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0001', '91930004', 'Allergy to eggs', 'http://snomed.info/sct', '雞蛋過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0002', '213020009', 'Egg protein allergy', 'http://snomed.info/sct', '雞蛋蛋白過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0003', '91932007', 'Allergy to fruit', 'http://snomed.info/sct', '水果過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0004', '91934008', 'Nut allergy', 'http://snomed.info/sct', '堅果過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0005', '91935009', 'Allergy to peanuts', 'http://snomed.info/sct', '花生過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0006', '91940001', 'Allergy to walnut', 'http://snomed.info/sct', '核桃過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0007', '91937001', 'Seafood allergy', 'http://snomed.info/sct', '海鮮過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0008', '91938006', 'Allergy to strawberries', 'http://snomed.info/sct', '草莓過敏', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0009', '15911003', 'Cow''s milk protein sensitivity', 'http://snomed.info/sct', '牛奶蛋白敏感', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0010', '700094005', 'Milk intolerance', 'http://snomed.info/sct', '牛奶不耐症', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0011', '25868003', 'Soy protein sensitivity', 'http://snomed.info/sct', '大豆蛋白敏感', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0012', '61712006', 'Transient gluten sensitivity', 'http://snomed.info/sct', '暫時性麩質敏感', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0013', '235719002', 'Food intolerance', 'http://snomed.info/sct', '食物不耐症', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-F0014', '267425008', 'Lactose intolerance', 'http://snomed.info/sct', '乳糖不耐症', '食物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0001', '232346004', 'Allergy to cat dander', 'http://snomed.info/sct', '貓皮屑過敏', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0002', '232347008', 'Allergy to animal dander', 'http://snomed.info/sct', '動物皮屑過敏', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0003', '188336009', 'Laboratory animal dander allergy', 'http://snomed.info/sct', '實驗動物皮屑過敏', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0004', '232348003', 'Feather allergy', 'http://snomed.info/sct', '羽毛過敏', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0005', '232349006', 'House dust allergy', 'http://snomed.info/sct', '灰塵過敏', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0006', '232350006', 'House dust mite allergy', 'http://snomed.info/sct', '塵蟎過敏', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0007', '35097006', 'Flea antigen', 'http://snomed.info/sct', '跳蚤抗原（過敏）', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0008', '200848004', 'Allergic contact dermatitis due to plants, except food', 'http://snomed.info/sct', '植物引起的接觸性過敏性皮膚炎（食物除外）', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-E0009', '4940008', 'Tattoo dye', 'http://snomed.info/sct', '刺青染料', '環境或動物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0001', '59037007', 'Drug intolerance', 'http://snomed.info/sct', '藥物不耐症', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0002', '91929009', 'Anti-infectives allergy', 'http://snomed.info/sct', '抗感染藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0003', '294461000', 'Antibacterial drug allergy', 'http://snomed.info/sct', '抗菌藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0004', '91936005', 'Penicillin allergy', 'http://snomed.info/sct', '盤尼西林（青黴素）過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0005', '294505008', 'Amoxicillin allergy', 'http://snomed.info/sct', '阿莫西林過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0006', '294532003', 'Cephalosporin allergy', 'http://snomed.info/sct', '頭孢菌素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0007', '91931000', 'Erythromycin allergy', 'http://snomed.info/sct', '紅黴素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0008', '91933002', 'Macrolide allergy', 'http://snomed.info/sct', '巨環類抗生素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0009', '91939003', 'Sulfonamide allergy', 'http://snomed.info/sct', '磺胺類藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0010', '294462007', 'Aminoglycosides allergy', 'http://snomed.info/sct', '氨基醣苷類抗生素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0011', '294469003', 'Gentamicin allergy', 'http://snomed.info/sct', '慶大黴素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0012', '293582004', 'Analgesic allergy', 'http://snomed.info/sct', '鎮痛藥過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0013', '293584003', 'Acetaminophen allergy', 'http://snomed.info/sct', '普拿疼（乙醯胺酚）過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0014', '293586001', 'Aspirin allergy', 'http://snomed.info/sct', '阿斯匹靈過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0015', '293610009', 'Non-steroidal anti-inflammatory drug allergy', 'http://snomed.info/sct', '非類固醇消炎止痛藥 (NSAID) 過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0016', '293619005', 'Ibuprofen allergy', 'http://snomed.info/sct', '布洛芬過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0017', '293613006', 'Diclofenac allergy', 'http://snomed.info/sct', '雙氯芬酸過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0018', '293625009', 'Naproxen allergy', 'http://snomed.info/sct', '萘普生過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0019', '293620004', 'Indometacin allergy', 'http://snomed.info/sct', '吲哚美辛過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0020', '293601001', 'Morphine allergy', 'http://snomed.info/sct', '嗎啡過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0021', '293597001', 'Codeine allergy', 'http://snomed.info/sct', '可待因過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0022', '293605005', 'Fentanyl allergy', 'http://snomed.info/sct', '吩坦尼過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0023', '293606006', 'Pethidine allergy', 'http://snomed.info/sct', '哌替啶過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0024', '293704003', 'General anesthetic drug allergy', 'http://snomed.info/sct', '全身麻醉藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0025', '293718005', 'Local anesthetic drug allergy', 'http://snomed.info/sct', '局部麻醉藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0026', '293722000', 'Lidocaine allergy', 'http://snomed.info/sct', '利多卡因過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0027', '293727006', 'Procaine allergy', 'http://snomed.info/sct', '普魯卡因過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0028', '293723005', 'Cocaine allergy', 'http://snomed.info/sct', '古柯鹼過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0029', '293637006', 'Contrast media allergy', 'http://snomed.info/sct', '顯影劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0030', '293638001', 'X-ray contrast media allergy', 'http://snomed.info/sct', 'X光顯影劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0031', '293816000', 'Antidepressant drug allergy', 'http://snomed.info/sct', '抗憂鬱藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0032', '293821002', 'Tricyclic antidepressant drug allergy', 'http://snomed.info/sct', '三環抗憂鬱藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0033', '293829000', 'Amitriptyline allergy', 'http://snomed.info/sct', '阿米替林過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0034', '293844004', 'Selective serotonin re-uptake inhibitor allergy', 'http://snomed.info/sct', '選擇性血清素回收抑制劑 (SSRI) 過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0035', '293850009', 'Fluoxetine allergy', 'http://snomed.info/sct', '氟西汀過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0036', '293845003', 'Sertraline allergy', 'http://snomed.info/sct', '舍曲林過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0037', '293857007', 'Antiepileptic allergy', 'http://snomed.info/sct', '抗癲癇藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0038', '293867002', 'Carbamazepine allergy', 'http://snomed.info/sct', '卡馬西平過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0039', '293869004', 'Phenytoin allergy', 'http://snomed.info/sct', '苯妥英過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0040', '293862008', 'Sodium valproate allergy', 'http://snomed.info/sct', '丙戊酸鈉過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0041', '293873001', 'Sedative allergy', 'http://snomed.info/sct', '鎮靜劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0042', '293885009', 'Benzodiazepine sedative allergy', 'http://snomed.info/sct', '苯二氮平類鎮靜劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0043', '293902006', 'Diazepam allergy', 'http://snomed.info/sct', '地西泮（安定）過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0044', '293903001', 'Lorazepam allergy', 'http://snomed.info/sct', '勞拉西泮過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0045', '293904007', 'Temazepam allergy', 'http://snomed.info/sct', '替馬西泮過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0046', '293913009', 'Neuroleptic allergy', 'http://snomed.info/sct', '神經阻斷劑（抗精神病藥）過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0047', '293924006', 'Haloperidol allergy', 'http://snomed.info/sct', '氟哌啶醇過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0048', '293962009', 'Beta-adrenoceptor blocking drug allergy', 'http://snomed.info/sct', '乙型交感神經阻斷劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0049', '293982008', 'Propranolol allergy', 'http://snomed.info/sct', '普萘洛爾過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0050', '293965006', 'Atenolol allergy', 'http://snomed.info/sct', '阿替洛爾過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0051', '293970004', 'Metoprolol allergy', 'http://snomed.info/sct', '美托洛爾過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0052', '293994004', 'Calcium-channel blocker allergy', 'http://snomed.info/sct', '鈣離子通道阻斷劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0053', '293996002', 'Nifedipine allergy', 'http://snomed.info/sct', '硝苯地平過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0054', '294002003', 'Amlodipine allergy', 'http://snomed.info/sct', '氨氯地平過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0055', '294003008', 'Diltiazem allergy', 'http://snomed.info/sct', '地爾硫䓬過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0056', '294005001', 'Verapamil allergy', 'http://snomed.info/sct', '維拉帕米過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0057', '294065003', 'Anticholinergic allergy', 'http://snomed.info/sct', '抗膽鹼藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0058', '294076004', 'Atropine allergy', 'http://snomed.info/sct', '阿托品過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0059', '294162002', 'Allergy to inhaled corticosteroids', 'http://snomed.info/sct', '吸入型皮質類固醇過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0060', '294216002', 'Uricosuric agent allergy', 'http://snomed.info/sct', '促進尿酸排泄藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0061', '294220003', 'Allopurinol allergy', 'http://snomed.info/sct', '別嘌醇過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0062', '294221004', 'Skeletal muscle relaxant allergy', 'http://snomed.info/sct', '骨骼肌鬆弛劑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0063', '293798009', 'Ciclosporin allergy', 'http://snomed.info/sct', '環孢素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0064', '294340008', 'Antifungal drug allergy', 'http://snomed.info/sct', '抗黴菌藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0065', '294349009', 'Amphotericin allergy', 'http://snomed.info/sct', '兩性黴素過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0066', '294362008', 'Ketoconazole allergy', 'http://snomed.info/sct', '酮康唑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0067', '294365005', 'Fluconazole allergy', 'http://snomed.info/sct', '氟康唑過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0068', '294367002', 'Antiviral drug allergy', 'http://snomed.info/sct', '抗病毒藥物過敏', '藥物過敏'),
    ('AllergyIntolerance.allergyCode', 'Al-M0069', '294384008', 'Aciclovir allergy', 'http://snomed.info/sct', '阿昔洛韋過敏', '藥物過敏'),
    ('PractitionerRole.code', 'PR-001', '158965000', 'Medical practitioner', 'http://snomed.info/sct', '醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-002', '394802001', 'General medicine', 'http://snomed.info/sct', '一般科醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-003', '59058001', 'General physician', 'http://snomed.info/sct', '家醫科醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-004', '39677007', 'Internal medicine', 'http://snomed.info/sct', '內科醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-005', '304292004', 'Surgeon', 'http://snomed.info/sct', '外科醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-006', '11935004', 'Obstetrician and gynecologist', 'http://snomed.info/sct', '婦產科醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-007', '21365001', 'Professional dentist', 'http://snomed.info/sct', '牙醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-008', '309294001', 'Emergency physician', 'http://snomed.info/sct', '急診醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-009', '88189002', 'Anesthetist', 'http://snomed.info/sct', '麻醉醫師', '綜合與基本科別'),
    ('PractitionerRole.code', 'PR-010', '17561000', 'Cardiologist', 'http://snomed.info/sct', '心臟內科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-011', '71838004', 'Gastroenterologist', 'http://snomed.info/sct', '腸胃內科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-012', '56397003', 'Neurologist', 'http://snomed.info/sct', '神經內科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-013', '41672002', 'Respiratory disease specialist', 'http://snomed.info/sct', '胸腔內科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-014', '11911009', 'Nephrologist', 'http://snomed.info/sct', '腎臟科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-015', '61894003', 'Endocrinologist', 'http://snomed.info/sct', '內分泌科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-016', '45440000', 'Rheumatologist', 'http://snomed.info/sct', '風濕免疫科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-017', '310512001', 'Medical oncologist', 'http://snomed.info/sct', '腫瘤內科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-018', '18803008', 'Dermatologist', 'http://snomed.info/sct', '皮膚科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-019', '61345009', 'Otorhinolaryngologist', 'http://snomed.info/sct', '耳鼻喉科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-020', '24590004', 'Urologist', 'http://snomed.info/sct', '泌尿科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-021', '80584001', 'Psychiatrist', 'http://snomed.info/sct', '精神科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-022', '22731001', 'Orthopedic surgeon', 'http://snomed.info/sct', '骨科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-023', '8724009', 'Plastic surgeon', 'http://snomed.info/sct', '整形外科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-024', '422140007', 'Ophthalmologist', 'http://snomed.info/sct', '眼科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-025', '66862007', 'Radiologist', 'http://snomed.info/sct', '放射科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-026', '61207006', 'Medical pathologist', 'http://snomed.info/sct', '病理科醫師', '內外科次專科'),
    ('PractitionerRole.code', 'PR-027', '82296001', 'Pediatrician', 'http://snomed.info/sct', '兒科醫師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-028', '28411006', 'Neonatologist', 'http://snomed.info/sct', '新生兒科醫師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-029', '309383003', 'Pediatric surgeon', 'http://snomed.info/sct', '兒科外科醫師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-030', '90201008', 'Pedodontist', 'http://snomed.info/sct', '兒童牙科醫師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-031', '309330006', 'Pediatric cardiologist', 'http://snomed.info/sct', '兒科心臟科醫師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-032', '309334002', 'Pediatric neurologist', 'http://snomed.info/sct', '兒科神經科醫師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-033', '9371000175105', 'Adolescent medicine specialist', 'http://snomed.info/sct', '青少年醫學專家', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-034', '224562001', 'Pediatric nurse', 'http://snomed.info/sct', '兒科護理師', '兒童與青少年核心專科'),
    ('PractitionerRole.code', 'PR-035', '158994007', 'Nurse', 'http://snomed.info/sct', '護理師', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-036', '224535009', 'Registered nurse', 'http://snomed.info/sct', '註冊護理師', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-037', '6816002', 'Specialized nurse', 'http://snomed.info/sct', '專科護理師', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-038', '224571005', 'Nurse practitioner', 'http://snomed.info/sct', '執業護理師', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-039', '415506007', 'Operating room nurse', 'http://snomed.info/sct', '手術室護理師', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-040', '224537001', 'Emergency nurse', 'http://snomed.info/sct', '急診護理師', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-041', '106294002', 'Midwifery personnel', 'http://snomed.info/sct', '助產人員', '護理與助產人員'),
    ('PractitionerRole.code', 'PR-042', '46255001', 'Pharmacist', 'http://snomed.info/sct', '藥師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-043', '159016003', 'Medical radiographer', 'http://snomed.info/sct', '醫事放射師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-044', '36682004', 'Physiotherapist', 'http://snomed.info/sct', '物理治療師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-045', '80546007', 'Occupational therapist', 'http://snomed.info/sct', '職能治療師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-046', '159026005', 'Speech and language therapist', 'http://snomed.info/sct', '語言治療師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-047', '442867008', 'Respiratory therapist', 'http://snomed.info/sct', '呼吸治療師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-048', '40127002', 'Dietitian', 'http://snomed.info/sct', '營養師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-049', '310191001', 'Clinical psychologist', 'http://snomed.info/sct', '臨床心理師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-050', '307988006', 'Medical technologist', 'http://snomed.info/sct', '醫事檢驗師', '醫事檢驗、放射與其他治療師'),
    ('PractitionerRole.code', 'PR-051', 'B', '中醫師', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '中醫師', '台灣專用代碼 (TW Core 限定)'),
    ('PractitionerRole.code', 'PR-052', 'X', '諮商心理師', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '諮商心理師', '台灣專用代碼 (TW Core 限定)'),
    ('PractitionerRole.code', 'PR-053', 'T', '醫事放射士', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '醫事放射士', '台灣專用代碼 (TW Core 限定)'),
    ('PractitionerRole.specialty', 'Spec-001', '419772000', 'Family practice', 'http://snomed.info/sct', '家庭醫學科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-002', '394802001', 'General medicine', 'http://snomed.info/sct', '一般醫學科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-003', '408443003', 'General medical practice', 'http://snomed.info/sct', '全科醫療', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-004', '394576009', 'Accident & emergency', 'http://snomed.info/sct', '急診醫學科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-005', '394811001', 'Geriatric medicine', 'http://snomed.info/sct', '老年醫學科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-006', '394806003', 'Palliative care', 'http://snomed.info/sct', '安寧療護科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-007', '409968004', 'Preventive medicine', 'http://snomed.info/sct', '預防醫學科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-008', '394821009', 'Occupational medicine', 'http://snomed.info/sct', '職業醫學科', '一般與綜合科別'),
    ('PractitionerRole.specialty', 'Spec-009', '419192003', 'Internal medicine', 'http://snomed.info/sct', '內科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-010', '394579002', 'Cardiology', 'http://snomed.info/sct', '心臟內科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-011', '394584008', 'Gastroenterology', 'http://snomed.info/sct', '胃腸肝膽科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-012', '394590007', 'Thoracic medicine', 'http://snomed.info/sct', '胸腔內科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-013', '394589003', 'Nephrology', 'http://snomed.info/sct', '腎臟科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-014', '394591006', 'Neurology', 'http://snomed.info/sct', '神經內科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-015', '394583002', 'Endocrinology', 'http://snomed.info/sct', '新陳代謝/內分泌科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-016', '394810000', 'Rheumatology', 'http://snomed.info/sct', '風濕免疫科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-017', '394807007', 'Infectious diseases', 'http://snomed.info/sct', '感染科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-018', '394593009', 'Medical oncology', 'http://snomed.info/sct', '血液腫瘤科', '內科系統'),
    ('PractitionerRole.specialty', 'Spec-019', '394609007', 'General surgery', 'http://snomed.info/sct', '一般外科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-020', '394801008', 'Trauma and orthopedics', 'http://snomed.info/sct', '骨科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-021', '394612005', 'Urology', 'http://snomed.info/sct', '泌尿科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-022', '394610002', 'Neurosurgery', 'http://snomed.info/sct', '神經外科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-023', '394611003', 'Plastic surgery', 'http://snomed.info/sct', '整形外科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-024', '408466002', 'Surgical-Cardiac surgery', 'http://snomed.info/sct', '心臟血管外科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-025', '408464004', 'Surgical-Colorectal surgery', 'http://snomed.info/sct', '大腸直腸外科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-026', '408463005', 'Vascular surgery', 'http://snomed.info/sct', '血管外科', '外科系統'),
    ('PractitionerRole.specialty', 'Spec-027', '394585009', 'Obstetrics and gynecology', 'http://snomed.info/sct', '婦產科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-028', '394594003', 'Ophthalmology', 'http://snomed.info/sct', '眼科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-029', '418960008', 'Otolaryngology', 'http://snomed.info/sct', '耳鼻喉科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-030', '394582007', 'Dermatology', 'http://snomed.info/sct', '皮膚科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-031', '394587001', 'Psychiatry', 'http://snomed.info/sct', '精神科/身心科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-032', '394602003', 'Rehabilitation', 'http://snomed.info/sct', '復健科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-033', '394577000', 'Anesthetics', 'http://snomed.info/sct', '麻醉科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-034', '394914008', 'Radiology', 'http://snomed.info/sct', '放射線科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-035', '394915009', 'General pathology', 'http://snomed.info/sct', '病理科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-036', '408478003', 'Critical care medicine', 'http://snomed.info/sct', '重症醫學科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-037', '394649004', 'Nuclear medicine', 'http://snomed.info/sct', '核子醫學科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-038', '419815003', 'Radiation oncology', 'http://snomed.info/sct', '放射腫瘤科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-039', '394882004', 'Pain management', 'http://snomed.info/sct', '疼痛科', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-040', '408450004', 'Sleep studies', 'http://snomed.info/sct', '睡眠醫學中心', '其他專科'),
    ('PractitionerRole.specialty', 'Spec-041', '408444009', 'Dental-general dental practice', 'http://snomed.info/sct', '一般牙科', '牙科系統'),
    ('PractitionerRole.specialty', 'Spec-042', '408465003', 'Oral and maxillofacial surgery', 'http://snomed.info/sct', '口腔顎面外科', '牙科系統'),
    ('PractitionerRole.specialty', 'Spec-043', '394608004', 'Orthodontics', 'http://snomed.info/sct', '齒顎矯正科', '牙科系統'),
    ('PractitionerRole.specialty', 'Spec-044', '408461007', 'Periodontal surgery', 'http://snomed.info/sct', '牙周病科', '牙科系統'),
    ('PractitionerRole.specialty', 'Spec-045', '394582007', 'Pediatrics', 'http://snomed.info/sct', '兒科', '兒科系統'),
    ('PractitionerRole.specialty', 'Spec-046', '394539006', 'Pediatric surgery', 'http://snomed.info/sct', '兒童外科', '兒科系統'),
    ('PractitionerRole.specialty', 'Spec-047', '394607009', 'Pediatric dentistry', 'http://snomed.info/sct', '兒童牙科', '兒科系統'),
    ('PractitionerRole.specialty', 'Spec-048', '408459003', 'Pediatric cardiology', 'http://snomed.info/sct', '兒童心臟科', '兒科系統'),
    ('PractitionerRole.specialty', 'Spec-049', '309334002', 'Pediatric neurology', 'http://snomed.info/sct', '兒童神經科', '兒科系統'),
    ('PractitionerRole.specialty', 'Spec-050', '394588006', 'Child and adolescent psychiatry', 'http://snomed.info/sct', '兒童與青少年精神科', '兒科系統'),
    ('Practitioner.qualification.code', 'Qual-01', '158965000', 'Medical practitioner', 'http://snomed.info/sct', '醫師', '核心醫護藥執照'),
    ('Practitioner.qualification.code', 'Qual-02', 'B', '中醫師', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '中醫師', '核心醫護藥執照'),
    ('Practitioner.qualification.code', 'Qual-03', '106289002', 'Dentist', 'http://snomed.info/sct', '牙醫師', '核心醫護藥執照'),
    ('Practitioner.qualification.code', 'Qual-04', '46255001', 'Pharmacist', 'http://snomed.info/sct', '藥師', '核心醫護藥執照'),
    ('Practitioner.qualification.code', 'Qual-05', '158994007', 'Nurse', 'http://snomed.info/sct', '護理師', '核心醫護藥執照'),
    ('Practitioner.qualification.code', 'Qual-06', '106294002', 'Midwifery personnel', 'http://snomed.info/sct', '助產師', '核心醫護藥執照'),
    ('Practitioner.qualification.code', 'Qual-07', '307988006', 'Medical technician', 'http://snomed.info/sct', '醫事檢驗師', '醫事檢驗與放射執照'),
    ('Practitioner.qualification.code', 'Qual-08', '159016003', 'Medical radiographer', 'http://snomed.info/sct', '醫事放射師', '醫事檢驗與放射執照'),
    ('Practitioner.qualification.code', 'Qual-09', 'T', '醫事放射士', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '醫事放射士', '醫事檢驗與放射執照'),
    ('Practitioner.qualification.code', 'Qual-10', 'K', '醫事檢驗生', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '醫事檢驗生', '醫事檢驗與放射執照'),
    ('Practitioner.qualification.code', 'Qual-11', '36682004', 'Physiotherapist', 'http://snomed.info/sct', '物理治療師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-12', '80546007', 'Occupational therapist', 'http://snomed.info/sct', '職能治療師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-13', '159026005', 'Speech and language therapist', 'http://snomed.info/sct', '語言治療師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-14', '442867008', 'Respiratory therapist (occupation)', 'http://snomed.info/sct', '呼吸治療師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-15', '40127002', 'Dietitian (general)', 'http://snomed.info/sct', '營養師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-16', '310191001', 'Clinical psychologist', 'http://snomed.info/sct', '臨床心理師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-17', 'X', '諮商心理師', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '諮商心理師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-18', '309418004', 'Audiologist', 'http://snomed.info/sct', '聽力師', '各類治療師與心理師執照'),
    ('Practitioner.qualification.code', 'Qual-19', '160008000', 'Dental technician', 'http://snomed.info/sct', '牙體技術師', '牙體與驗光執照'),
    ('Practitioner.qualification.code', 'Qual-20', '4', '牙體技術生', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '牙體技術生', '牙體與驗光執照'),
    ('Practitioner.qualification.code', 'Qual-21', '28229004', 'Optometrist', 'http://snomed.info/sct', '驗光師', '牙體與驗光執照'),
    ('Practitioner.qualification.code', 'Qual-22', '6', '驗光生', 'https://twcore.mohw.gov.tw/ig/twcore/CodeSystem/health-professional-tw', '驗光生', '牙體與驗光執照')
ON CONFLICT (mapping_key, source_code) DO UPDATE SET
    target_code = EXCLUDED.target_code,
    target_display = EXCLUDED.target_display,
    target_system = EXCLUDED.target_system,
    display_zh_tw = EXCLUDED.display_zh_tw,
    group_name = EXCLUDED.group_name,
    is_active = TRUE;
